# Licensed under the Apache-2.0 license

[alias]
rriscv32imac = "run --release --target=riscv32imac-unknown-none-elf --example"
rrv32imac = "rriscv32imac"
rriscv32imc = "run --release --target=riscv32imc-unknown-none-elf --example"
rrv32imc = "rriscv32imc"

# Common settings for all embedded targets
[target.'cfg(target_arch = "riscv32")']
rustflags = [
    "-C", "relocation-model=static",
    "-C", "link-arg=-icf=all",
]
runner = ["cargo", "run", "-p", "runner", "--release"]