// Licensed under the Apache-2.0 license

//! VENDOR_DEFINED request dispatch for SPDM-Lite.

use mcu_spdm_lite_codec::{
    ReqRespCode, SpdmMsgHdrPdu, StandardsBodyId, VendorDefinedReqPdu, VendorDefinedRspPdu,
    WireReader, WireWriter,
};
use mcu_spdm_lite_traits::{
    PalBytes, SpdmPal, SpdmPalIo, SpdmPalIoKind, SpdmPalIoTransport,
};
use zerocopy::{little_endian::U16, FromBytes};

use crate::build::build_error_response;
use crate::chunk::effective_data_transfer_size;
use crate::error::{
    SpdmResult, SPDM_INVALID_REQUEST, SPDM_UNEXPECTED_REQUEST, SPDM_UNSPECIFIED,
    SPDM_UNSUPPORTED_REQUEST, SPDM_VERSION_MISMATCH,
};
use crate::stack::{ConnectionState, Phase};

/// SPDM-Lite VDM extension hook.
///
/// Handlers receive the decoded VDM payload only; the SPDM
/// VENDOR_DEFINED envelope is parsed and generated by the stack.
pub trait VdmHandler: Sync {
    fn match_id(
        &self,
        standard_id: StandardsBodyId,
        vendor_id: &[u8],
        secure_session: bool,
    ) -> bool;

    fn handle_request(&self, req: &[u8], rsp: &mut [u8]) -> SpdmResult<usize>;
}

pub(crate) fn handle_vendor_defined_request<'a, Pal: SpdmPal>(
    state: &mut ConnectionState<Pal::State>,
    pal: &'a Pal,
    io: &<Pal as SpdmPalIoTransport>::Io<'_>,
    handlers: &[&dyn VdmHandler],
) -> SpdmResult<PalBytes<'a, Pal>> {
    if (state.phase as u8) < (Phase::AfterAlgorithms as u8) {
        return Err(SPDM_UNEXPECTED_REQUEST);
    }

    let req = io.request();
    if req.len() > pal.mtu() {
        return Err(SPDM_INVALID_REQUEST);
    }

    let (hdr, body) = SpdmMsgHdrPdu::ref_from_prefix(req).map_err(|_| SPDM_INVALID_REQUEST)?;
    if hdr.version != state.version.to_u8() {
        return Err(SPDM_VERSION_MISMATCH);
    }

    let mut reader = WireReader::new(body);
    let req_pdu = reader.read::<VendorDefinedReqPdu>()?;
    let standard_id =
        StandardsBodyId::from_u16(req_pdu.standard_id.get()).ok_or(SPDM_INVALID_REQUEST)?;
    let Some(expected_vendor_id_len) = standard_id.vendor_id_len() else {
        return unsupported_request(pal, io, state.version);
    };
    if req_pdu.vendor_id_len != expected_vendor_id_len {
        return Err(SPDM_INVALID_REQUEST);
    }

    let vendor_id = reader.take(req_pdu.vendor_id_len as usize)?;
    let req_len = reader.read::<U16>()?.get() as usize;
    let vdm_req = reader.take(req_len)?;
    if !reader.is_empty() {
        return Err(SPDM_INVALID_REQUEST);
    }

    let secure_session = io.kind() == SpdmPalIoKind::SecuredMessage;
    let Some(handler) = handlers
        .iter()
        .copied()
        .find(|handler| handler.match_id(standard_id, vendor_id, secure_session))
    else {
        return unsupported_request(pal, io, state.version);
    };

    build_vendor_defined_response(
        state,
        pal,
        io,
        standard_id,
        vendor_id,
        vdm_req,
        handler,
    )
}

fn unsupported_request<'a, Pal: SpdmPal>(
    pal: &'a Pal,
    io: &<Pal as SpdmPalIoTransport>::Io<'_>,
    version: mcu_spdm_lite_codec::SpdmVersion,
) -> SpdmResult<PalBytes<'a, Pal>> {
    build_error_response(
        pal,
        io,
        version,
        SPDM_UNSUPPORTED_REQUEST.spec_byte(),
        ReqRespCode::VENDOR_DEFINED_REQUEST.0,
        &[],
    )
}

fn build_vendor_defined_response<'a, Pal: SpdmPal>(
    state: &ConnectionState<Pal::State>,
    pal: &'a Pal,
    io: &<Pal as SpdmPalIoTransport>::Io<'_>,
    standard_id: StandardsBodyId,
    vendor_id: &[u8],
    vdm_req: &[u8],
    handler: &dyn VdmHandler,
) -> SpdmResult<PalBytes<'a, Pal>> {
    let fixed_len = SpdmMsgHdrPdu::SIZE
        + VendorDefinedRspPdu::SIZE
        + vendor_id.len()
        + core::mem::size_of::<U16>();
    let max_rsp_len = effective_data_transfer_size(state, pal)
        .checked_sub(fixed_len)
        .ok_or(SPDM_UNSPECIFIED)?;
    if max_rsp_len > u16::MAX as usize {
        return Err(SPDM_UNSPECIFIED);
    }

    let head = pal.header_size();
    let mut rsp = pal.alloc_bytes(io, head + fixed_len + max_rsp_len)?;
    let payload_len_offset =
        head + SpdmMsgHdrPdu::SIZE + VendorDefinedRspPdu::SIZE + vendor_id.len();
    let payload_offset = payload_len_offset + core::mem::size_of::<U16>();

    {
        let mut writer = WireWriter::new(&mut rsp[head..payload_offset]);
        writer.write(&SpdmMsgHdrPdu::new(
            state.version,
            ReqRespCode::VENDOR_DEFINED_RESPONSE,
        ))?;
        writer.write(&VendorDefinedRspPdu {
            param1: 0,
            param2: 0,
            standard_id: U16::new(standard_id.as_u16()),
            vendor_id_len: vendor_id.len() as u8,
        })?;
        writer.write_bytes(vendor_id)?;
        writer.write(&U16::new(0))?;
    }

    let rsp_len = handler.handle_request(vdm_req, &mut rsp[payload_offset..])?;
    if rsp_len > max_rsp_len || rsp_len > u16::MAX as usize {
        return Err(SPDM_UNSPECIFIED);
    }
    rsp[payload_len_offset..payload_len_offset + core::mem::size_of::<U16>()]
        .copy_from_slice(&(rsp_len as u16).to_le_bytes());
    Pal::shrink_bytes(&mut rsp, head + fixed_len + rsp_len)?;
    Ok(rsp)
}
