// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-rtl repo at 0e43b8e7011c1c8761e114bc949fcad6cf30538e
// , caliptra-ss repo at 9911c2b0e4bac9e4b48f6c2155c86cb116159734
// , and i3c-core repo at d5c715103f529ade0e5d375a53c5692daaa9c54b
//
pub mod bits {
    //! Types that represent individual registers (bitfields).
    use tock_registers::register_bitfields;
    register_bitfields! {
        u32,
            Meie [
                /// External interrupt enable
                Inten OFFSET(0) NUMBITS(1) [],
            ],
            Meigwctrl [
                /// External interrupt polarity
                /// 0b0: Active-high interrupt
                /// 0b1: Active-low interrupt
                Polarity OFFSET(0) NUMBITS(1) [],
                /// External interrupt type
                /// 0b0: Level-triggered interrupt
                /// 0b1: Edge-triggered interrupt
                Inttype OFFSET(1) NUMBITS(1) [],
            ],
            Meipl [
                /// External interrupt priority level
                Priority OFFSET(0) NUMBITS(4) [],
            ],
            Meip [
                /// External interrupt pending
                Intpend OFFSET(0) NUMBITS(1) [],
            ],
            Mpiccfg [
                /// Interrupt priority order
                /// 0b0: RISC-V standard compliant priority order (0=lowest to 15=highest)
                /// 0b1: Reverse priority order (15=lowest to 0=highest)
                Priord OFFSET(0) NUMBITS(1) [],
            ],
    }
}
