// Licensed under the Apache-2.0 license.
//
// generated by caliptra_mcu_registers_generator with caliptra-ss repo at 198681a6e95cd2a6ac293dc9a870ca1f76c8c45e
//
#![recursion_limit = "2048"]
#![no_std]
pub mod axicdma;
pub mod defines;
pub mod doe_mbox;
pub mod el2_pic_ctrl;
pub mod ethernet;
pub mod fuses;
pub mod i3c;
pub mod lc_ctrl;
pub mod mbox;
pub mod mci;
pub mod otp_ctrl;
pub mod primary_flash_ctrl;
pub mod secondary_flash_ctrl;
pub mod sha512_acc;
pub mod soc;
pub mod usb_combo;
pub mod usb_dev0_mem;
pub mod usb_dev1;
pub mod usb_dev1_mem;
pub mod usbdev;
