// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 1933efd6bc8d60918a35ee4ddfda7938acda654c
//
pub const SECONDARY_FLASH_CTRL_ADDR: u32 = 0x2000_8800;
