// Licensed under the Apache-2.0 license.
//
// generated by caliptra_mcu_registers_generator with caliptra-ss repo at 198681a6e95cd2a6ac293dc9a870ca1f76c8c45e
//
pub const SECONDARY_FLASH_CTRL_ADDR: u32 = 0x2000_8800;
