// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at aaa49a4be2af25002369a0e662ad63a490b86e70
//
pub const SECONDARY_FLASH_CTRL_ADDR: u32 = 0x2000_8800;
