// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 2b7c4bf60cde3101c4287d31213164d1767ce33e
//
pub const TEST_SRAM_ADDR: u32 = 0xb00c_0000;
pub mod regs {
    //! Types that represent registers.
    use tock_registers::register_structs;
    register_structs! {
        pub TestSram {
            (0x0 => pub sram: [tock_registers::registers::ReadWrite<u32>; 262144]),
            (0x100000 => @END),
        }
    }
}
