// Licensed under the Apache-2.0 license.
//
// generated by caliptra_mcu_registers_generator with caliptra-ss repo at 198681a6e95cd2a6ac293dc9a870ca1f76c8c45e
//
pub const USB_DEV1_MEM_ADDR: u32 = 0x3000_1000;
pub mod regs {
    //! Types that represent registers.
    use tock_registers::register_structs;
    register_structs! {
        pub UsbDev1Mem {
            (0x0 => pub usb_dev1_mem: [tock_registers::registers::ReadWrite<u32>; 1024]),
            (0x1000 => @END),
        }
    }
}
