# Licensed under the Apache-2.0 license

[workspace]
members = [
    "emulator/app",
    "emulator/compliance-test",
    "emulator/examples",
    "emulator/bus",
    "emulator/cpu",
    "emulator/derive",
    "emulator/periph",
    "emulator/types",
    "runtime",
    "runtime/apps/pldm",
    "xtask",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Caliptra contributors"]

[workspace.dependencies]
arrayref = "0.3.6"
bitfield = "0.14.0"
bit-vec = "0.6.3"
clap = { version = "4.5.11", features = [
    "cargo",
    "derive",
    "env",
    "string",
    "unicode",
    "wrap_help",
] }
clap_derive = "4.5.11"
console = "0.15.8"
elf = "0.7.4"
emulator-bus = { path = "emulator/bus" }
emulator-cpu = { path = "emulator/cpu" }
emulator-derive = { path = "emulator/derive" }
emulator-periph = { path = "emulator/periph" }
emulator-types = { path = "emulator/types" }
getrandom = "0.2"
gdbstub = "0.6.3"
gdbstub_arch = "0.2.4"
hex = "0.4.3"
lazy_static = "1.4.0"
proc-macro2 = "1.0.66"
quote = "1.0"
syn = "1.0.107"
tock-registers = { git = "https://github.com/tock/tock.git" }
ctrlc = "3.4.5"
serde = { version = "1.0.209", features = ["alloc", "derive", "serde_derive"] }
serde_json = { version = "1.0.127", features = ["alloc"] }


# Always optimize the emulator during tests, as it is a major bottleneck for
# test speed.
[profile.test.package.emulator-bus]
opt-level = 3
[profile.test.package.emulator-cpu]
opt-level = 3
[profile.test.package.emulator-periph]
opt-level = 3
[profile.test.package.emulator-types]
opt-level = 3
[profile.test.package.tock-registers]
opt-level = 3
