# Licensed under the Apache-2.0 license

[toolchain]
channel = "1.81"
components = ["clippy", "rust-src", "llvm-tools", "rustfmt", "rustc-dev"]
targets = ["x86_64-unknown-linux-gnu", "riscv32imc-unknown-none-elf"]
profile = "default"
