# Licensed under the Apache-2.0 license

[package]
name = "spdm-lib"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
arrayvec.workspace = true
async-trait.workspace = true
bitfield.workspace = true
caliptra-api.workspace = true
constant_time_eq.workspace = true
libapi-caliptra.workspace = true
libsyscall-caliptra.workspace = true
libtock_platform.workspace = true
libtock_console.workspace = true
zerocopy.workspace = true
ocp-eat.workspace = true

[dev-dependencies]
rand.workspace = true
