// Example C application using the Caliptra Utility Host Library

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

// Include the generated C header (would be generated by cbindgen)
// #include "caliptra_util_host.h"

// For now, we'll define the structures manually as an example
typedef enum {
    CALIPTRA_SUCCESS = 0,
    CALIPTRA_ERROR = -1,
    CALIPTRA_INVALID_PARAM = -2,
    CALIPTRA_TRANSPORT_ERROR = -3,
    CALIPTRA_COMMAND_NOT_FOUND = -4,
} CaliptraUtilResult;

typedef enum {
    TRANSPORT_MCTP = 0,
    TRANSPORT_DOE = 1,
    TRANSPORT_TCP = 2,
} CTransportType;

typedef enum {
    CMD_SPDM = 0,
    CMD_PLDM = 1,
    CMD_MAILBOX = 2,
    CMD_CERTIFICATE = 3,
} CCommandType;

typedef struct {
    CCommandType command_type;
    uint32_t opcode;
    const uint8_t* payload_data;
    size_t payload_size;
} CCommand;

typedef struct {
    int success;
    uint8_t* response_data;
    size_t response_size;
    char* error_message;
    uint32_t execution_time_ms;
} CCommandResult;

// Opaque handle (would be defined in the actual header)
typedef struct CaliptraUtilHostHandle CaliptraUtilHostHandle;

// Function declarations (would be in the actual header)
CaliptraUtilResult caliptra_util_host_init(void);
CaliptraUtilHostHandle* caliptra_util_host_create_mctp(uint8_t endpoint_id);
CaliptraUtilHostHandle* caliptra_util_host_create_doe(void);
void caliptra_util_host_destroy(CaliptraUtilHostHandle* handle);
CaliptraUtilResult caliptra_util_host_connect(CaliptraUtilHostHandle* handle);
CaliptraUtilResult caliptra_util_host_disconnect(CaliptraUtilHostHandle* handle);
int caliptra_util_host_is_connected(CaliptraUtilHostHandle* handle);
CaliptraUtilResult caliptra_util_host_execute_command(
    CaliptraUtilHostHandle* handle,
    const CCommand* command,
    CCommandResult* result
);
CaliptraUtilResult caliptra_util_host_register_builtin_handlers(CaliptraUtilHostHandle* handle);
void caliptra_util_host_free_result(CCommandResult* result);

// Mock implementations for demonstration
CaliptraUtilResult caliptra_util_host_init(void) {
    printf("Initializing Caliptra Utility Host Library\\n");
    return CALIPTRA_SUCCESS;
}

CaliptraUtilHostHandle* caliptra_util_host_create_mctp(uint8_t endpoint_id) {
    printf("Creating MCTP transport with endpoint ID: 0x%02X\\n", endpoint_id);
    return (CaliptraUtilHostHandle*)0x12345678; // Mock handle
}

CaliptraUtilHostHandle* caliptra_util_host_create_doe(void) {
    printf("Creating DOE transport\\n");
    return (CaliptraUtilHostHandle*)0x87654321; // Mock handle
}

void caliptra_util_host_destroy(CaliptraUtilHostHandle* handle) {
    if (handle) {
        printf("Destroying host handle\\n");
    }
}

CaliptraUtilResult caliptra_util_host_connect(CaliptraUtilHostHandle* handle) {
    if (!handle) return CALIPTRA_INVALID_PARAM;
    printf("Connecting transport\\n");
    return CALIPTRA_SUCCESS;
}

CaliptraUtilResult caliptra_util_host_disconnect(CaliptraUtilHostHandle* handle) {
    if (!handle) return CALIPTRA_INVALID_PARAM;
    printf("Disconnecting transport\\n");
    return CALIPTRA_SUCCESS;
}

int caliptra_util_host_is_connected(CaliptraUtilHostHandle* handle) {
    return handle ? 1 : 0;
}

CaliptraUtilResult caliptra_util_host_execute_command(
    CaliptraUtilHostHandle* handle,
    const CCommand* command,
    CCommandResult* result
) {
    if (!handle || !command || !result) {
        return CALIPTRA_INVALID_PARAM;
    }
    
    printf("Executing command - Type: %d, Opcode: 0x%08X\\n", 
           command->command_type, command->opcode);
    
    // Mock successful response
    result->success = 1;
    result->execution_time_ms = 42;
    
    // Allocate mock response data
    uint8_t mock_response[] = {0x10, 0x84, 0x00, 0x01, 0x00};
    result->response_size = sizeof(mock_response);
    result->response_data = malloc(result->response_size);
    if (result->response_data) {
        memcpy(result->response_data, mock_response, result->response_size);
    }
    
    result->error_message = NULL;
    
    return CALIPTRA_SUCCESS;
}

CaliptraUtilResult caliptra_util_host_register_builtin_handlers(CaliptraUtilHostHandle* handle) {
    if (!handle) return CALIPTRA_INVALID_PARAM;
    printf("Registering built-in command handlers\\n");
    return CALIPTRA_SUCCESS;
}

void caliptra_util_host_free_result(CCommandResult* result) {
    if (result) {
        if (result->response_data) {
            free(result->response_data);
            result->response_data = NULL;
            result->response_size = 0;
        }
        if (result->error_message) {
            free(result->error_message);
            result->error_message = NULL;
        }
    }
}

// Helper functions
void print_hex_data(const uint8_t* data, size_t size) {
    printf("[");
    for (size_t i = 0; i < size; i++) {
        printf("0x%02X", data[i]);
        if (i < size - 1) printf(", ");
    }
    printf("]\\n");
}

int test_spdm_commands(CaliptraUtilHostHandle* host) {
    printf("\\n=== Testing SPDM Commands ===\\n");
    
    // Test SPDM GET_VERSION
    uint8_t spdm_payload[] = {0x00};
    CCommand cmd = {
        .command_type = CMD_SPDM,
        .opcode = 0x84, // GET_VERSION
        .payload_data = spdm_payload,
        .payload_size = sizeof(spdm_payload)
    };
    
    CCommandResult result = {0};
    CaliptraUtilResult status = caliptra_util_host_execute_command(host, &cmd, &result);
    
    if (status == CALIPTRA_SUCCESS && result.success) {
        printf("SPDM GET_VERSION: SUCCESS\\n");
        printf("  Execution time: %u ms\\n", result.execution_time_ms);
        printf("  Response (%zu bytes): ", result.response_size);
        print_hex_data(result.response_data, result.response_size);
    } else {
        printf("SPDM GET_VERSION: FAILED\\n");
        if (result.error_message) {
            printf("  Error: %s\\n", result.error_message);
        }
    }
    
    caliptra_util_host_free_result(&result);
    return status == CALIPTRA_SUCCESS ? 0 : -1;
}

int test_pldm_commands(CaliptraUtilHostHandle* host) {
    printf("\\n=== Testing PLDM Commands ===\\n");
    
    // Test PLDM GET_TID
    CCommand cmd = {
        .command_type = CMD_PLDM,
        .opcode = 0x02, // GET_TID
        .payload_data = NULL,
        .payload_size = 0
    };
    
    CCommandResult result = {0};
    CaliptraUtilResult status = caliptra_util_host_execute_command(host, &cmd, &result);
    
    if (status == CALIPTRA_SUCCESS && result.success) {
        printf("PLDM GET_TID: SUCCESS\\n");
        printf("  Execution time: %u ms\\n", result.execution_time_ms);
        printf("  Response (%zu bytes): ", result.response_size);
        print_hex_data(result.response_data, result.response_size);
    } else {
        printf("PLDM GET_TID: FAILED\\n");
        if (result.error_message) {
            printf("  Error: %s\\n", result.error_message);
        }
    }
    
    caliptra_util_host_free_result(&result);
    return status == CALIPTRA_SUCCESS ? 0 : -1;
}

int test_mailbox_commands(CaliptraUtilHostHandle* host) {
    printf("\\n=== Testing Mailbox Commands ===\\n");
    
    // Test Mailbox GET_IDEV_CSR
    CCommand cmd = {
        .command_type = CMD_MAILBOX,
        .opcode = 0x50030000, // GET_IDEV_CSR
        .payload_data = NULL,
        .payload_size = 0
    };
    
    CCommandResult result = {0};
    CaliptraUtilResult status = caliptra_util_host_execute_command(host, &cmd, &result);
    
    if (status == CALIPTRA_SUCCESS && result.success) {
        printf("Mailbox GET_IDEV_CSR: SUCCESS\\n");
        printf("  Execution time: %u ms\\n", result.execution_time_ms);
        printf("  Response (%zu bytes): ", result.response_size);
        print_hex_data(result.response_data, result.response_size);
    } else {
        printf("Mailbox GET_IDEV_CSR: FAILED\\n");
        if (result.error_message) {
            printf("  Error: %s\\n", result.error_message);
        }
    }
    
    caliptra_util_host_free_result(&result);
    return status == CALIPTRA_SUCCESS ? 0 : -1;
}

int main(int argc, char* argv[]) {
    printf("Caliptra Utility Host Library - C Example\\n");
    printf("==========================================\\n\\n");
    
    // Initialize the library
    CaliptraUtilResult status = caliptra_util_host_init();
    if (status != CALIPTRA_SUCCESS) {
        fprintf(stderr, "Failed to initialize library\\n");
        return 1;
    }
    
    // Choose transport based on command line argument
    CaliptraUtilHostHandle* host = NULL;
    
    if (argc > 1 && strcmp(argv[1], "doe") == 0) {
        printf("Using DOE transport\\n");
        host = caliptra_util_host_create_doe();
    } else {
        printf("Using MCTP transport (endpoint ID: 0x1D)\\n");
        host = caliptra_util_host_create_mctp(0x1D);
    }
    
    if (!host) {
        fprintf(stderr, "Failed to create host instance\\n");
        return 1;
    }
    
    // Register built-in handlers
    status = caliptra_util_host_register_builtin_handlers(host);
    if (status != CALIPTRA_SUCCESS) {
        fprintf(stderr, "Failed to register command handlers\\n");
        caliptra_util_host_destroy(host);
        return 1;
    }
    
    // Connect to the transport
    printf("\\nConnecting to transport...\\n");
    status = caliptra_util_host_connect(host);
    if (status != CALIPTRA_SUCCESS) {
        fprintf(stderr, "Failed to connect to transport\\n");
        caliptra_util_host_destroy(host);
        return 1;
    }
    
    printf("Connected: %s\\n", caliptra_util_host_is_connected(host) ? "Yes" : "No");
    
    // Run tests
    int test_result = 0;
    test_result |= test_spdm_commands(host);
    test_result |= test_pldm_commands(host);
    test_result |= test_mailbox_commands(host);
    
    // Cleanup
    printf("\\n=== Cleanup ===\\n");
    caliptra_util_host_disconnect(host);
    caliptra_util_host_destroy(host);
    
    printf("\\nExample completed %s\\n", test_result == 0 ? "successfully" : "with errors");
    return test_result;
}