# Licensed under the Apache-2.0 license

[package]
name = "spdm-lib"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
bitfield.workspace = true
zerocopy.workspace = true
libsyscall-caliptra.workspace = true
libtock_platform.workspace = true
libtock_console.workspace = true
thiserror-no-std.workspace = true

[dev-dependencies]
rand.workspace = true