# Licensed under the Apache-2.0 license

[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
semver = "1.0.23"
walkdir = "2.5.0"
proc-macro2.workspace = true
clap.workspace = true
registers-generator.workspace = true
registers-systemrdl.workspace = true
quote.workspace = true
tempfile = "3.13.0"
