# Licensed under the Apache-2.0 license

[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
semver = "1.0.23"
tempfile = "3.14.0"
walkdir = "2.5.0"
proc-macro2.workspace = true
clap.workspace = true
elf.workspace = true
registers-generator.workspace = true
registers-systemrdl.workspace = true
quote.workspace = true
crc32fast = "1.4.2"
zerocopy.workspace = true
