[package]
edition = "2021"
name = "syscalls_tests"
rust-version.workspace = true
version = "0.1.0"

[dependencies]
libtock_platform = { path = "../platform" }
libtock_unittest = { path = "../unittest" }
