// Licensed under the Apache-2.0 license

use std::env;
use std::fmt::Write;
use std::fs;
use std::path::PathBuf;

use caliptra_ocp_eat::ocp_profile::{
    IntegrityRegisterEntry, IntegrityRegisterIdChoice, TaggedConciseEvidence,
};
use caliptra_ocp_eat::{
    CborEncodable, CborEncoder, ClassIdTypeChoice, ClassMap, ConciseEvidence, ConciseEvidenceMap,
    DigestEntry, EnvironmentMap, EvTriplesMap, EvidenceTripleRecord, MeasurementMap,
    MeasurementValue, TaggedBytes,
};

const EVIDENCE_DIGEST_SIZE: usize = 48;
const EVIDENCE_MEASUREMENT_KEY: u64 = 1;
const EVIDENCE_INTEGRITY_REGISTER_ID: u64 = 0;
const EVIDENCE_SHA384_ALG_ID: i32 = 7;
const TEMPLATE_CLASS_ID: &[u8; 10] = b"CLASSID000";
const TEMPLATE_VENDOR: &str = "CALIPTRA_TEMPLATE_VENDOR";
const TEMPLATE_MODEL: &str = "CALIPTRA_TEMPLATE_MODEL";
const TEMPLATE_SVN: u64 = 0x0102_0304_0506_0708;

fn main() {
    let current_digest = digest_marker(0x10);
    let journey_digest = digest_marker(0x60);
    let measurement_map = encode_measurement_map(&current_digest, &journey_digest);
    let evidence_triple = encode_evidence_triple(&current_digest, &journey_digest);
    let concise_evidence = encode_empty_concise_evidence();

    let svn_marker = encode_uint(TEMPLATE_SVN);
    let vendor_marker = encode_text(TEMPLATE_VENDOR);
    let model_marker = encode_text(TEMPLATE_MODEL);

    let svn_pos = find_once(&measurement_map, &svn_marker, "measurement svn");
    let current_pos = find_once_from(
        &measurement_map,
        &current_digest,
        svn_pos + svn_marker.len(),
        "current digest",
    );
    let journey_pos = find_once_from(
        &measurement_map,
        &journey_digest,
        current_pos + current_digest.len(),
        "journey digest",
    );

    let class_id_pos = find_once(&evidence_triple, TEMPLATE_CLASS_ID, "class id");
    let vendor_pos = find_once_from(
        &evidence_triple,
        &vendor_marker,
        class_id_pos + TEMPLATE_CLASS_ID.len(),
        "vendor text",
    );
    let model_pos = find_once_from(
        &evidence_triple,
        &model_marker,
        vendor_pos + vendor_marker.len(),
        "model text",
    );
    let measurement_map_pos = find_once_from(
        &evidence_triple,
        &measurement_map,
        model_pos + model_marker.len(),
        "measurement map",
    );

    let empty_array = [0x80];
    let evidence_array_pos = find_once(&concise_evidence, &empty_array, "evidence triples array");

    let mut generated = String::new();
    generated.push_str("// @generated by runtime/userspace/api/measurement-api/build.rs\n");
    generated.push_str("// Template fragments are derived from caliptra-ocp-eat.\n\n");
    write_bytes_const(
        &mut generated,
        "CONCISE_EVIDENCE_PREFIX",
        &concise_evidence[..evidence_array_pos],
    );
    write_bytes_const(
        &mut generated,
        "CONCISE_EVIDENCE_SUFFIX",
        &concise_evidence[evidence_array_pos + empty_array.len()..],
    );
    write_bytes_const(
        &mut generated,
        "EVIDENCE_TRIPLE_CLASS_PREFIX",
        &evidence_triple[..class_id_pos],
    );
    write_bytes_const(
        &mut generated,
        "CLASS_VENDOR_KEY",
        &evidence_triple[class_id_pos + TEMPLATE_CLASS_ID.len()..vendor_pos],
    );
    write_bytes_const(
        &mut generated,
        "CLASS_MODEL_KEY",
        &evidence_triple[vendor_pos + vendor_marker.len()..model_pos],
    );
    write_bytes_const(
        &mut generated,
        "SINGLE_MEASUREMENT_ARRAY_PREFIX",
        &evidence_triple[model_pos + model_marker.len()..measurement_map_pos],
    );
    write_bytes_const(
        &mut generated,
        "EVIDENCE_TRIPLE_SUFFIX",
        &evidence_triple[measurement_map_pos + measurement_map.len()..],
    );
    write_bytes_const(
        &mut generated,
        "MEASUREMENT_VALUE_PREFIX",
        &measurement_map[..svn_pos],
    );
    write_bytes_const(
        &mut generated,
        "CURRENT_DIGEST_PREFIX",
        &measurement_map[svn_pos + svn_marker.len()..current_pos],
    );
    write_bytes_const(
        &mut generated,
        "JOURNEY_DIGEST_PREFIX",
        &measurement_map[current_pos + current_digest.len()..journey_pos],
    );
    write_bytes_const(
        &mut generated,
        "MEASUREMENT_VALUE_SUFFIX",
        &measurement_map[journey_pos + journey_digest.len()..],
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    fs::write(out_dir.join("evidence_templates.rs"), generated)
        .expect("write generated evidence templates");
}

fn digest_marker(start: u8) -> [u8; EVIDENCE_DIGEST_SIZE] {
    let mut out = [0u8; EVIDENCE_DIGEST_SIZE];
    for (idx, byte) in out.iter_mut().enumerate() {
        *byte = start.wrapping_add(idx as u8);
    }
    out
}

fn encode_empty_concise_evidence() -> Vec<u8> {
    let triples: [EvidenceTripleRecord<'_>; 0] = [];
    let evidence = ConciseEvidence::Tagged(TaggedConciseEvidence {
        concise_evidence: ConciseEvidenceMap {
            ev_triples: EvTriplesMap {
                evidence_triples: Some(&triples),
                identity_triples: None,
                dependency_triples: None,
                membership_triples: None,
                coswid_triples: None,
                attest_key_triples: None,
            },
            evidence_id: None,
            profile: None,
        },
    });
    encode_to_vec(&evidence)
}

fn encode_evidence_triple(
    current_digest: &[u8; EVIDENCE_DIGEST_SIZE],
    journey_digest: &[u8; EVIDENCE_DIGEST_SIZE],
) -> Vec<u8> {
    let digest = [DigestEntry {
        alg_id: EVIDENCE_SHA384_ALG_ID,
        value: current_digest,
    }];
    let integrity_digest = [DigestEntry {
        alg_id: EVIDENCE_SHA384_ALG_ID,
        value: journey_digest,
    }];
    let integrity_registers = [IntegrityRegisterEntry {
        id: IntegrityRegisterIdChoice::Uint(EVIDENCE_INTEGRITY_REGISTER_ID),
        digests: &integrity_digest,
    }];
    let measurements = [MeasurementMap {
        key: EVIDENCE_MEASUREMENT_KEY,
        mval: MeasurementValue {
            version: None,
            svn: Some(TEMPLATE_SVN),
            digests: Some(&digest),
            integrity_registers: Some(&integrity_registers),
            raw_value: None,
            raw_value_mask: None,
        },
    }];
    let triple = EvidenceTripleRecord {
        environment: EnvironmentMap {
            class: ClassMap {
                class_id: ClassIdTypeChoice::TaggedBytes(TaggedBytes::new(TEMPLATE_CLASS_ID)),
                vendor: Some(TEMPLATE_VENDOR),
                model: Some(TEMPLATE_MODEL),
            },
        },
        measurements: &measurements,
    };
    encode_to_vec(&triple)
}

fn encode_measurement_map(
    current_digest: &[u8; EVIDENCE_DIGEST_SIZE],
    journey_digest: &[u8; EVIDENCE_DIGEST_SIZE],
) -> Vec<u8> {
    let digest = [DigestEntry {
        alg_id: EVIDENCE_SHA384_ALG_ID,
        value: current_digest,
    }];
    let integrity_digest = [DigestEntry {
        alg_id: EVIDENCE_SHA384_ALG_ID,
        value: journey_digest,
    }];
    let integrity_registers = [IntegrityRegisterEntry {
        id: IntegrityRegisterIdChoice::Uint(EVIDENCE_INTEGRITY_REGISTER_ID),
        digests: &integrity_digest,
    }];
    let measurement = MeasurementMap {
        key: EVIDENCE_MEASUREMENT_KEY,
        mval: MeasurementValue {
            version: None,
            svn: Some(TEMPLATE_SVN),
            digests: Some(&digest),
            integrity_registers: Some(&integrity_registers),
            raw_value: None,
            raw_value_mask: None,
        },
    };
    encode_to_vec(&measurement)
}

fn encode_to_vec<T: CborEncodable>(value: &T) -> Vec<u8> {
    let mut out = [0u8; 1024];
    let len = {
        let mut encoder = CborEncoder::new(&mut out);
        value.encode(&mut encoder).expect("encode template source");
        encoder.len()
    };
    out[..len].to_vec()
}

fn encode_uint(value: u64) -> Vec<u8> {
    encode_type_value(0, value)
}

fn encode_text(text: &str) -> Vec<u8> {
    let mut out = encode_type_value(3, text.len() as u64);
    out.extend_from_slice(text.as_bytes());
    out
}

fn encode_type_value(major_type: u8, value: u64) -> Vec<u8> {
    let major = major_type << 5;
    if value <= 23 {
        vec![major | value as u8]
    } else if value <= 0xff {
        vec![major | 24, value as u8]
    } else if value <= 0xffff {
        let mut out = vec![major | 25];
        out.extend_from_slice(&(value as u16).to_be_bytes());
        out
    } else if value <= 0xffff_ffff {
        let mut out = vec![major | 26];
        out.extend_from_slice(&(value as u32).to_be_bytes());
        out
    } else {
        let mut out = vec![major | 27];
        out.extend_from_slice(&value.to_be_bytes());
        out
    }
}

fn find_once(haystack: &[u8], needle: &[u8], name: &str) -> usize {
    find_once_from(haystack, needle, 0, name)
}

fn find_once_from(haystack: &[u8], needle: &[u8], start: usize, name: &str) -> usize {
    haystack[start..]
        .windows(needle.len())
        .position(|window| window == needle)
        .map(|pos| start + pos)
        .unwrap_or_else(|| panic!("template marker not found: {name}"))
}

fn write_bytes_const(output: &mut String, name: &str, bytes: &[u8]) {
    writeln!(output, "const {name}: &[u8] = &[").expect("write const header");
    for chunk in bytes.chunks(12) {
        output.push_str("    ");
        for byte in chunk {
            write!(output, "0x{byte:02x}, ").expect("write const byte");
        }
        output.push('\n');
    }
    output.push_str("];\n\n");
}
