# Licensed under the Apache-2.0 license

[package]
name = "example-app"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
critical-section = "1.1.2"
embassy-executor = { version = "0.6.3", features = ["nightly"] }
libtock = { path = "../libtock" }
libtock_alarm = { path = "../libtock/apis/peripherals/alarm" }
libtock_console = { path = "../libtock/apis/interface/console" }
libtock_debug_panic = { path = "../libtock/panic_handlers/debug_panic" }
libtock_platform = { path = "../libtock/platform" }
libtock_runtime = { path = "../libtock/runtime" }
libtockasync = { path = "../libtockasync" }
libtock_caliptra = { path = "../apis" }
portable-atomic = "1.7.0"

[target.'cfg(not(target_arch = "riscv32"))'.dependencies]
embassy-executor = { version = "0.6.3", features = ["arch-riscv32", "nightly"] }
libtock_unittest = { path = "../libtock/unittest" }

[target.'cfg(target_arch = "riscv32")'.dependencies]
embedded-alloc = "0.5.1"

[features]
default = []
test-i3c-simple = []
test-i3c-constant-writes = []
test-flash-ctrl-init = []
test-flash-ctrl-read-write-page = []
test-flash-ctrl-erase-page = []
test-flash-storage-read-write = []
test-flash-storage-erase = []
test-mctp-ctrl-cmds = []
test-mctp-capsule-loopback = []
test-mctp-user-loopback = []
