// Licensed under the Apache-2.0 license

//! Allocator-backed COSE_Sign1 EAT token generation via byte templates.

use mcu_caliptra_api::{
    mldsa87_compute_mu, sha_finish, sha_init, sha_update, ApiAlloc, HashAlgo, DPE_MLDSA87_MU_SIZE,
    MLDSA87_TR_SIZE, SHA_CONTEXT_SIZE,
};
use mcu_error::codes::INVARIANT;
use mcu_error::McuResult;

use super::common::{cbor_bstr_len, write_type_header};

include!(concat!(env!("OUT_DIR"), "/eat_cose_template.rs"));

pub const PAYLOAD_HEADER_OFFSET: usize = COSE_PREAMBLE_LEN + KID_LEN;
pub const PAYLOAD_OFFSET: usize = PAYLOAD_HEADER_OFFSET + PAYLOAD_BSTR_HEADER_LEN;
pub const SHA384_DIGEST_SIZE: usize = 48;

/// Supported COSE signing algorithm for OCP EAT.
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum OcpEatAlgorithm {
    Esp384,
    Mldsa87,
}

impl OcpEatAlgorithm {
    pub const fn cose_preamble(self) -> &'static [u8] {
        match self {
            Self::Esp384 => ESP384_COSE_PREAMBLE,
            Self::Mldsa87 => MLDSA87_COSE_PREAMBLE,
        }
    }

    pub const fn sig_preamble(self) -> &'static [u8] {
        match self {
            Self::Esp384 => ESP384_SIG_PREAMBLE,
            Self::Mldsa87 => MLDSA87_SIG_PREAMBLE,
        }
    }

    pub const fn sig_bstr_header(self) -> &'static [u8] {
        match self {
            Self::Esp384 => ESP384_SIG_BSTR_HEADER,
            Self::Mldsa87 => MLDSA87_SIG_BSTR_HEADER,
        }
    }

    pub const fn signature_size(self) -> usize {
        match self {
            Self::Esp384 => ESP384_SIGNATURE_SIZE,
            Self::Mldsa87 => MLDSA87_SIGNATURE_SIZE,
        }
    }
}

pub const fn cose_sign1_len(payload_len: usize, algo: OcpEatAlgorithm) -> usize {
    COSE_PREAMBLE_LEN
        + KID_LEN
        + cbor_bstr_len(payload_len)
        + algo.sig_bstr_header().len()
        + algo.signature_size()
}

/// EAT signer backed by [`ApiAlloc`].
///
/// This type only encodes COSE and hashes the Sig_structure. Callers provide
/// signatures generated by Measurement API so DPE handle updates stay
/// centralized.
pub struct SignedEat {
    algo: OcpEatAlgorithm,
}

impl Default for SignedEat {
    fn default() -> Self {
        Self::new(OcpEatAlgorithm::Esp384)
    }
}

impl SignedEat {
    pub const fn new(algo: OcpEatAlgorithm) -> Self {
        Self { algo }
    }

    #[allow(dead_code)]
    pub const fn algo(&self) -> OcpEatAlgorithm {
        self.algo
    }

    /// Write the fixed COSE prefix and return the final `kid` slot inside
    /// `eat_buffer`.
    pub fn prepare_in_place<'a>(
        &self,
        eat_buffer: &'a mut [u8],
    ) -> McuResult<&'a mut [u8; KID_LEN]> {
        if eat_buffer.len() < PAYLOAD_OFFSET {
            return Err(INVARIANT);
        }

        let preamble = self.algo.cose_preamble();
        let preamble_slot = eat_buffer.get_mut(..COSE_PREAMBLE_LEN).ok_or(INVARIANT)?;
        if preamble_slot.len() != preamble.len() {
            return Err(INVARIANT);
        }
        preamble_slot.copy_from_slice(preamble);
        let kid_slot = eat_buffer
            .get_mut(COSE_PREAMBLE_LEN..PAYLOAD_HEADER_OFFSET)
            .and_then(|s| s.first_chunk_mut::<KID_LEN>())
            .ok_or(INVARIANT)?;
        Ok(kid_slot)
    }

    /// Return the final payload slot inside `eat_buffer`.
    pub fn payload_buffer_mut<'a>(
        &self,
        eat_buffer: &'a mut [u8],
        max_payload_len: usize,
    ) -> McuResult<&'a mut [u8]> {
        let end = PAYLOAD_OFFSET
            .checked_add(max_payload_len)
            .ok_or(INVARIANT)?;
        eat_buffer.get_mut(PAYLOAD_OFFSET..end).ok_or(INVARIANT)
    }

    /// Return the already-encoded final payload inside `eat_buffer`.
    pub fn payload_slice<'a>(
        &self,
        eat_buffer: &'a [u8],
        payload_len: usize,
    ) -> McuResult<&'a [u8]> {
        let end = PAYLOAD_OFFSET.checked_add(payload_len).ok_or(INVARIANT)?;
        eat_buffer.get(PAYLOAD_OFFSET..end).ok_or(INVARIANT)
    }

    /// Finish a COSE_Sign1 EAT token whose payload and kid are already in their
    /// final locations in `eat_buffer`.
    #[cfg(test)]
    pub fn finish_in_place(
        &self,
        payload_len: usize,
        signature: &[u8],
        eat_buffer: &mut [u8],
    ) -> McuResult<usize> {
        let (cose_len, sig_slot) = self.signature_buffer_mut(payload_len, eat_buffer)?;
        if sig_slot.len() != signature.len() {
            return Err(INVARIANT);
        }
        sig_slot.copy_from_slice(signature);
        Ok(cose_len)
    }

    /// Finalize the COSE_Sign1 layout and return the final signature slot.
    pub fn signature_buffer_mut<'a>(
        &self,
        payload_len: usize,
        eat_buffer: &'a mut [u8],
    ) -> McuResult<(usize, &'a mut [u8])> {
        let cose_len = cose_sign1_len(payload_len, self.algo);
        if eat_buffer.len() < cose_len {
            return Err(INVARIANT);
        }

        // Write the minimal (canonical) COSE payload bstr header. The payload
        // was staged at `PAYLOAD_OFFSET` assuming a reserved 3-byte header, so
        // when the canonical header is shorter, compact the payload left. This
        // keeps the token deterministic and matches the Sig_structure hashed by
        // `sig_context_digest`, which also uses the minimal header.
        let header_len = write_cose_payload_bstr_len(
            eat_buffer
                .get_mut(PAYLOAD_HEADER_OFFSET..PAYLOAD_OFFSET)
                .ok_or(INVARIANT)?,
            payload_len,
        )?;
        if header_len > PAYLOAD_BSTR_HEADER_LEN {
            return Err(INVARIANT);
        }
        let payload_start = PAYLOAD_HEADER_OFFSET
            .checked_add(header_len)
            .ok_or(INVARIANT)?;
        if header_len < PAYLOAD_BSTR_HEADER_LEN {
            let src_end = PAYLOAD_OFFSET.checked_add(payload_len).ok_or(INVARIANT)?;
            if src_end > eat_buffer.len() {
                return Err(INVARIANT);
            }
            eat_buffer.copy_within(PAYLOAD_OFFSET..src_end, payload_start);
        }

        let sig_bstr_header = self.algo.sig_bstr_header();
        let sig_size = self.algo.signature_size();
        let sig_header_offset = payload_start.checked_add(payload_len).ok_or(INVARIANT)?;
        let sig_offset = sig_header_offset
            .checked_add(sig_bstr_header.len())
            .ok_or(INVARIANT)?;
        let sig_end = sig_offset.checked_add(sig_size).ok_or(INVARIANT)?;

        let sig_hdr_end = sig_header_offset
            .checked_add(sig_bstr_header.len())
            .ok_or(INVARIANT)?;
        let sig_hdr_slot = eat_buffer
            .get_mut(sig_header_offset..sig_hdr_end)
            .ok_or(INVARIANT)?;
        if sig_hdr_slot.len() != sig_bstr_header.len() {
            return Err(INVARIANT);
        }
        sig_hdr_slot.copy_from_slice(sig_bstr_header);
        let sig_slot = eat_buffer.get_mut(sig_hdr_end..sig_end).ok_or(INVARIANT)?;

        Ok((cose_len, sig_slot))
    }

    /// Calculate the Sig_structure digest (P-384) or external `mu` (ML-DSA-87)
    /// into `signing_input`.
    #[inline(never)]
    pub async fn sig_context_input<A: ApiAlloc>(
        &self,
        alloc: &A,
        tr: &[u8; MLDSA87_TR_SIZE],
        payload: &[u8],
        signing_input: &mut [u8],
    ) -> McuResult<()> {
        let mut payload_header = [0u8; 9];
        let payload_header_len = write_cose_payload_bstr_len(&mut payload_header, payload.len())?;
        let payload_header = payload_header.get(..payload_header_len).ok_or(INVARIANT)?;
        match self.algo {
            OcpEatAlgorithm::Esp384 => {
                let digest_out = signing_input
                    .get_mut(..SHA384_DIGEST_SIZE)
                    .and_then(|s| s.first_chunk_mut::<SHA384_DIGEST_SIZE>())
                    .ok_or(INVARIANT)?;
                let sha_buf = alloc.alloc(SHA_CONTEXT_SIZE)?;
                let mut state =
                    sha_init(alloc, sha_buf, HashAlgo::Sha384, self.algo.sig_preamble()).await?;
                sha_update(alloc, &mut state, payload_header).await?;
                sha_update(alloc, &mut state, payload).await?;
                sha_finish(alloc, &mut state, digest_out).await
            }
            OcpEatAlgorithm::Mldsa87 => {
                let mu_out = signing_input
                    .get_mut(..DPE_MLDSA87_MU_SIZE)
                    .and_then(|s| s.first_chunk_mut::<DPE_MLDSA87_MU_SIZE>())
                    .ok_or(INVARIANT)?;
                mldsa87_compute_mu(
                    alloc,
                    tr,
                    &[],
                    &[self.algo.sig_preamble(), payload_header, payload],
                    mu_out,
                )
                .await
            }
        }
    }
}

fn write_cose_payload_bstr_len(out: &mut [u8], len: usize) -> McuResult<usize> {
    write_type_header(out, 2, len as u64)
}

#[cfg(test)]
mod tests {
    use super::*;
    use coset::TaggedCborSerializable;
    extern crate std;
    use std::vec::Vec;

    fn expected_bstr_header(len: usize) -> Vec<u8> {
        if len <= 23 {
            std::vec![0x40 | len as u8]
        } else if len <= 255 {
            std::vec![0x58, len as u8]
        } else {
            std::vec![0x59, (len >> 8) as u8, (len & 0xff) as u8]
        }
    }

    fn assert_in_place_layout(payload_len: usize, algo: OcpEatAlgorithm) {
        let signer = SignedEat::new(algo);
        let payload: Vec<u8> = (0..payload_len).map(|i| (i % 251) as u8).collect();
        let kid = [0x5a; KID_LEN];
        let signature = std::vec![0xc3; algo.signature_size()];
        let mut out = std::vec![0u8; cose_sign1_len(payload_len, algo)];

        *signer.prepare_in_place(&mut out).unwrap() = kid;
        signer
            .payload_buffer_mut(&mut out, payload_len)
            .unwrap()
            .copy_from_slice(&payload);
        let encoded_len = signer
            .finish_in_place(payload_len, &signature, &mut out)
            .unwrap();

        let header = expected_bstr_header(payload_len);
        let payload_start = PAYLOAD_HEADER_OFFSET + header.len();
        let sig_header_offset = payload_start + payload_len;

        assert_eq!(encoded_len, out.len());
        assert_eq!(encoded_len, cose_sign1_len(payload_len, algo));
        assert_eq!(&out[..COSE_PREAMBLE_LEN], algo.cose_preamble());
        assert_eq!(&out[COSE_PREAMBLE_LEN..PAYLOAD_HEADER_OFFSET], &kid);
        assert_eq!(
            &out[PAYLOAD_HEADER_OFFSET..payload_start],
            header.as_slice()
        );
        assert_eq!(&out[payload_start..sig_header_offset], payload.as_slice());
        assert_eq!(
            &out[sig_header_offset..sig_header_offset + algo.sig_bstr_header().len()],
            algo.sig_bstr_header()
        );
        assert_eq!(
            &out[sig_header_offset + algo.sig_bstr_header().len()..],
            signature.as_slice()
        );

        // Verify that coset parses the generated token and matches all headers and content
        // &out[..5] has outer tags (55799 and 61), followed by tagged COSE_Sign1 (tag 18) at index 5.
        let parsed = coset::CoseSign1::from_tagged_slice(&out[5..]).unwrap();
        match algo {
            OcpEatAlgorithm::Esp384 => {
                assert_eq!(
                    parsed.protected.header.alg,
                    Some(coset::RegisteredLabelWithPrivate::Assigned(
                        coset::iana::Algorithm::ESP384
                    ))
                );
            }
            OcpEatAlgorithm::Mldsa87 => {
                assert_eq!(
                    parsed.protected.header.alg,
                    Some(coset::RegisteredLabelWithPrivate::Assigned(
                        coset::iana::Algorithm::ML_DSA_87
                    ))
                );
            }
        }
        assert_eq!(
            parsed.protected.header.content_type,
            Some(coset::RegisteredLabel::Assigned(
                coset::iana::CoapContentFormat::EatCwt
            ))
        );
        assert_eq!(parsed.unprotected.key_id, kid);
        assert_eq!(parsed.payload, Some(payload));
        assert_eq!(parsed.signature, signature);
    }

    #[test]
    fn in_place_layout_places_kid_payload_and_signature_esp384() {
        for payload_len in [10usize, 100, 300] {
            assert_in_place_layout(payload_len, OcpEatAlgorithm::Esp384);
        }
    }

    #[test]
    fn in_place_layout_places_kid_payload_and_signature_mldsa87() {
        for payload_len in [10usize, 100, 300] {
            assert_in_place_layout(payload_len, OcpEatAlgorithm::Mldsa87);
        }
    }
}
