// Licensed under the Apache-2.0 license

//! Allocator-backed COSE_Sign1 EAT token generation via byte templates.

use mcu_caliptra_api_lite::{
    sha_finish, sha_init, sha_update, ApiAlloc, HashAlgo, SHA_CONTEXT_SIZE,
};
use mcu_error::codes::INVARIANT;
use mcu_error::McuResult;

use super::common::{cbor_bstr_len, write_type_header};

const KID_LEN: usize = 48;
const SHA384_DIGEST_SIZE: usize = 48;
const ECDSA_P384_SIGNATURE_SIZE: usize = 96;
const SIGNATURE_BSTR_HEADER: [u8; 2] = [0x58, 0x60];
const ES384_PROTECTED_HEADER: [u8; 5] = [0x44, 0xa1, 0x01, 0x38, 0x22];
const PAYLOAD_BSTR_HEADER_LEN: usize = 3;
const PAYLOAD_HEADER_OFFSET: usize = COSE_PREAMBLE.len() + KID_LEN;
const PAYLOAD_OFFSET: usize = PAYLOAD_HEADER_OFFSET + PAYLOAD_BSTR_HEADER_LEN;

// This signer currently supports only ES384/P-384. Keep algorithm-specific
// bytes isolated here so MLDSA87 can add another protected header/sign path.

// --- COSE_Sign1 byte layout ---
//
// d9 d9f7         TAG(55799) self-described CBOR
// d8 3d           TAG(61)    CWT
// d2              TAG(18)    COSE_Sign1
// 84              array(4)
// 44 a1 01 38 22  bstr(4) protected: {1: -35} (ES384)
// a1 04 58 30     unprotected: map(1) {4: bstr(48)} kid
// <48 bytes kid>
// <COSE payload bstr length prefix>
// <EAT claims payload>
// 58 60           bstr(96) signature
// <96 bytes signature>

#[rustfmt::skip]
const COSE_PREAMBLE: [u8; 16] = [
    0xd9, 0xd9, 0xf7,              // TAG(55799)
    0xd8, 0x3d,                     // TAG(61)
    0xd2,                           // TAG(18)
    0x84,                           // array(4)
    ES384_PROTECTED_HEADER[0], ES384_PROTECTED_HEADER[1], ES384_PROTECTED_HEADER[2],
    ES384_PROTECTED_HEADER[3], ES384_PROTECTED_HEADER[4],
    0xa1, 0x04, 0x58, 0x30,        // map(1) {4: bstr(48)}
];

// --- Sig_structure byte layout ---
//
// 84                          array(4)
// 6a "Signature1"             tstr(10)
// 44 a1 01 38 22              bstr(4) protected: {1: -35}
// 40                          bstr(0) external_aad
// <COSE payload bstr length prefix>
// <EAT claims payload>

#[rustfmt::skip]
const SIG_PREAMBLE: [u8; 18] = [
    0x84,                                                                // array(4)
    0x6a, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x31, // tstr(10) "Signature1"
    ES384_PROTECTED_HEADER[0], ES384_PROTECTED_HEADER[1], ES384_PROTECTED_HEADER[2],
    ES384_PROTECTED_HEADER[3], ES384_PROTECTED_HEADER[4],
    0x40,                                                                // bstr(0) empty
];

pub const fn cose_sign1_len(payload_len: usize) -> usize {
    COSE_PREAMBLE.len()
        + KID_LEN
        + cbor_bstr_len(payload_len)
        + SIGNATURE_BSTR_HEADER.len()
        + ECDSA_P384_SIGNATURE_SIZE
}

/// EAT signer backed by [`ApiAlloc`].
///
/// This type only encodes COSE and hashes the Sig_structure. Callers provide
/// signatures generated by Measurement API so DPE handle updates stay
/// centralized.
pub struct SignedEat;

impl Default for SignedEat {
    fn default() -> Self {
        Self::new()
    }
}

impl SignedEat {
    pub const fn new() -> Self {
        Self
    }

    /// Write the fixed COSE prefix and return the final `kid` slot inside
    /// `eat_buffer`.
    pub fn prepare_in_place<'a>(
        &self,
        eat_buffer: &'a mut [u8],
    ) -> McuResult<&'a mut [u8; KID_LEN]> {
        if eat_buffer.len() < PAYLOAD_OFFSET {
            return Err(INVARIANT);
        }

        let rest = eat_buffer;
        let (preamble_slot, rest) = rest
            .split_first_chunk_mut::<{ COSE_PREAMBLE.len() }>()
            .ok_or(INVARIANT)?;
        *preamble_slot = COSE_PREAMBLE;
        let (kid_slot, _) = rest.split_first_chunk_mut::<KID_LEN>().ok_or(INVARIANT)?;
        Ok(kid_slot)
    }

    /// Return the final payload slot inside `eat_buffer`.
    pub fn payload_buffer_mut<'a>(
        &self,
        eat_buffer: &'a mut [u8],
        max_payload_len: usize,
    ) -> McuResult<&'a mut [u8]> {
        let end = PAYLOAD_OFFSET
            .checked_add(max_payload_len)
            .ok_or(INVARIANT)?;
        eat_buffer.get_mut(PAYLOAD_OFFSET..end).ok_or(INVARIANT)
    }

    /// Return the already-encoded final payload inside `eat_buffer`.
    pub fn payload_slice<'a>(
        &self,
        eat_buffer: &'a [u8],
        payload_len: usize,
    ) -> McuResult<&'a [u8]> {
        let end = PAYLOAD_OFFSET.checked_add(payload_len).ok_or(INVARIANT)?;
        eat_buffer.get(PAYLOAD_OFFSET..end).ok_or(INVARIANT)
    }

    /// Finish a COSE_Sign1 EAT token whose payload and kid are already in their
    /// final locations in `eat_buffer`.
    pub fn finish_in_place(
        &self,
        payload_len: usize,
        signature: &[u8; ECDSA_P384_SIGNATURE_SIZE],
        eat_buffer: &mut [u8],
    ) -> McuResult<usize> {
        let cose_len = cose_sign1_len(payload_len);
        if eat_buffer.len() < cose_len {
            return Err(INVARIANT);
        }

        // Write the minimal (canonical) COSE payload bstr header. The payload
        // was staged at `PAYLOAD_OFFSET` assuming a reserved 3-byte header, so
        // when the canonical header is shorter, compact the payload left. This
        // keeps the token deterministic and matches the Sig_structure hashed by
        // `sig_context_digest`, which also uses the minimal header.
        let header_len = write_cose_payload_bstr_len(
            eat_buffer
                .get_mut(PAYLOAD_HEADER_OFFSET..PAYLOAD_OFFSET)
                .ok_or(INVARIANT)?,
            payload_len,
        )?;
        if header_len > PAYLOAD_BSTR_HEADER_LEN {
            return Err(INVARIANT);
        }
        let payload_start = PAYLOAD_HEADER_OFFSET
            .checked_add(header_len)
            .ok_or(INVARIANT)?;
        if header_len < PAYLOAD_BSTR_HEADER_LEN {
            let src_end = PAYLOAD_OFFSET.checked_add(payload_len).ok_or(INVARIANT)?;
            if src_end > eat_buffer.len() {
                return Err(INVARIANT);
            }
            eat_buffer.copy_within(PAYLOAD_OFFSET..src_end, payload_start);
        }

        let sig_header_offset = payload_start.checked_add(payload_len).ok_or(INVARIANT)?;
        let sig_offset = sig_header_offset
            .checked_add(SIGNATURE_BSTR_HEADER.len())
            .ok_or(INVARIANT)?;
        let sig_end = sig_offset
            .checked_add(ECDSA_P384_SIGNATURE_SIZE)
            .ok_or(INVARIANT)?;
        let (sig_hdr_slot, sig_slot) = eat_buffer
            .get_mut(sig_header_offset..sig_end)
            .and_then(|slot| slot.split_first_chunk_mut::<{ SIGNATURE_BSTR_HEADER.len() }>())
            .ok_or(INVARIANT)?;
        *sig_hdr_slot = SIGNATURE_BSTR_HEADER;
        sig_slot.copy_from_slice(signature);

        Ok(cose_len)
    }

    /// Hash the COSE Sig_structure for a COSE_Sign1 EAT token.
    pub async fn sig_context_digest<A: ApiAlloc>(
        &self,
        alloc: &A,
        payload: &[u8],
        digest_out: &mut [u8; SHA384_DIGEST_SIZE],
    ) -> McuResult<()> {
        let sha_buf = alloc.alloc(SHA_CONTEXT_SIZE)?;
        let mut state = sha_init(alloc, sha_buf, HashAlgo::Sha384, &SIG_PREAMBLE).await?;
        let mut payload_header = [0u8; 9];
        let payload_header_len = write_cose_payload_bstr_len(&mut payload_header, payload.len())?;
        let payload_header = payload_header.get(..payload_header_len).ok_or(INVARIANT)?;
        sha_update(alloc, &mut state, payload_header).await?;
        sha_update(alloc, &mut state, payload).await?;
        sha_finish(alloc, &mut state, digest_out).await
    }
}

fn write_cose_payload_bstr_len(out: &mut [u8], len: usize) -> McuResult<usize> {
    write_type_header(out, 2, len as u64)
}

#[cfg(test)]
mod tests {
    use super::*;
    extern crate std;
    use std::vec::Vec;

    fn expected_bstr_header(len: usize) -> Vec<u8> {
        if len <= 23 {
            std::vec![0x40 | len as u8]
        } else if len <= 255 {
            std::vec![0x58, len as u8]
        } else {
            std::vec![0x59, (len >> 8) as u8, (len & 0xff) as u8]
        }
    }

    fn assert_in_place_layout(payload_len: usize) {
        let signer = SignedEat::new();
        let payload: Vec<u8> = (0..payload_len).map(|i| (i % 251) as u8).collect();
        let kid = [0x5a; KID_LEN];
        let signature = [0xc3; ECDSA_P384_SIGNATURE_SIZE];
        let mut out = std::vec![0u8; cose_sign1_len(payload_len)];

        *signer.prepare_in_place(&mut out).unwrap() = kid;
        signer
            .payload_buffer_mut(&mut out, payload_len)
            .unwrap()
            .copy_from_slice(&payload);
        let encoded_len = signer
            .finish_in_place(payload_len, &signature, &mut out)
            .unwrap();

        let header = expected_bstr_header(payload_len);
        let payload_start = PAYLOAD_HEADER_OFFSET + header.len();
        let sig_header_offset = payload_start + payload_len;

        assert_eq!(encoded_len, out.len());
        assert_eq!(encoded_len, cose_sign1_len(payload_len));
        assert_eq!(&out[..COSE_PREAMBLE.len()], COSE_PREAMBLE);
        assert_eq!(&out[COSE_PREAMBLE.len()..PAYLOAD_HEADER_OFFSET], &kid);
        assert_eq!(
            &out[PAYLOAD_HEADER_OFFSET..payload_start],
            header.as_slice()
        );
        assert_eq!(&out[payload_start..sig_header_offset], payload.as_slice());
        assert_eq!(
            &out[sig_header_offset..sig_header_offset + SIGNATURE_BSTR_HEADER.len()],
            SIGNATURE_BSTR_HEADER
        );
        assert_eq!(
            &out[sig_header_offset + SIGNATURE_BSTR_HEADER.len()..],
            &signature
        );
    }

    #[test]
    fn in_place_layout_places_kid_payload_and_signature() {
        // 300 -> 3-byte header (no compaction); 100 -> 2-byte header (shift 1);
        // 10 -> 1-byte header (shift 2). The small cases are what the emulator
        // hits (concise evidence < 256) and previously errored out.
        for payload_len in [10usize, 100, 300] {
            assert_in_place_layout(payload_len);
        }
    }
}
