# Licensed under the Apache-2.0 license

[package]
name = "ocp-eat"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
libapi-caliptra.workspace = true
coset.workspace = true
