# Licensed under the Apache-2.0 license

[package]
name = "caliptra-mcu-network-app-boot-source"
version.workspace = true
edition.workspace = true
description = "Boot source provider application for the Network Coprocessor"

[dependencies]
caliptra-mcu-flash-image.workspace = true
zerocopy.workspace = true
