# Licensed under the Apache-2.0 license

[package]
name = "flash_api"
version = "0.1.0"
edition = "2021"


[dependencies]
libtock = { path = "../libtock" }
libtock_platform = { path = "../libtock/platform" }
libtockasync = { path = "../libtockasync" }

[dev-dependencies]
libtock_unittest = { path = "../libtock/unittest" }