# Licensed under the Apache-2.0 license

[package]
name = "emulator-bmc"
version = "0.1.0"
edition = "2021"

[dependencies]
caliptra-emu-bus.workspace = true
caliptra-emu-periph.workspace = true
emulator-bus.workspace = true
smlang.workspace = true
tock-registers.workspace = true
