// Licensed under the Apache-2.0 license
// Generated by xtask rdl-gen-firmware

#![no_std]

pub mod i3c;
pub mod mci;
pub mod mbox;
pub mod sha512_acc;
pub mod soc;
pub mod otp_ctrl;
pub mod lc_ctrl;
pub mod el2_pic_ctrl;
pub mod primary_flash_ctrl;
pub mod secondary_flash_ctrl;
pub mod axicdma;
pub mod doe_mbox;
