# Licensed under the Apache-2.0 license

[profile.nightly]
failure-output = "immediate-final"
fail-fast = false
slow-timeout = { period = "5m", terminate-after = 1 }

[profile.nightly.junit]
path = "/tmp/junit.xml"
store-success-output = true
store-failure-output = true

[profile.nightly-emulator]
failure-output = "immediate-final"
fail-fast = false
slow-timeout = { period = "30s", terminate-after = 30 }

[profile.nightly-emulator.junit]
path = "/tmp/junit.xml"
store-success-output = true
store-failure-output = true

[profile.nightly-ci]
inherits = "nightly"
default-filter = """
(package(mcu-hw-model)
    - test(model_emulated::test::test_new_unbooted)) |
(package(tests-integration) and test(test_mcu_mbox_prod_debug_unlock))
"""
