# Licensed under the Apache-2.0 license

[package]
name = "emulator-periph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayref.workspace = true
bitfield.workspace = true
emulator-bus.workspace = true
emulator-cpu.workspace = true
emulator-derive.workspace = true
emulator-registers-generated.workspace = true
emulator-types.workspace = true
lazy_static.workspace = true
num_enum.workspace = true
registers-generated.workspace = true
serde_json.workspace = true
serde.workspace = true
tock-registers.workspace = true
zerocopy.workspace = true

[dev-dependencies]
libc = "0.2"

[features]
default = []
test-i3c-constant-writes = []
test-flash-ctrl-read-write-page = []
test-flash-ctrl-erase-page = []
test-mctp-ctrl-cmds = []
test-flash-storage-read-write = []
test-flash-storage-erase = []
