# Licensed under the Apache-2.0 license

[package]
name = "libtock_caliptra"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
libtock_platform = { path = "../libtock/platform" }
libtockasync = { path = "../libtockasync" }
libtock_console = { path = "../libtock/apis/interface/console" }
