# Licensed under the Apache-2.0 license

[package]
name = "external-cmds-common"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace = true
zerocopy.workspace = true