// Licensed under the Apache-2.0 license.
//
// generated by caliptra_mcu_registers_generator with caliptra-ss repo at 198681a6e95cd2a6ac293dc9a870ca1f76c8c45e
//

use std::sync::atomic::{AtomicBool, Ordering};

static WARN_ON_STUB: AtomicBool = AtomicBool::new(false);

/// Enable or disable warning logs when auto-generated register stubs
/// handle a read/write that was not overridden by the peripheral implementation.
pub fn set_stub_warnings(enabled: bool) {
    WARN_ON_STUB.store(enabled, Ordering::Relaxed);
}

/// Returns `true` if stub warning logs are enabled.
#[inline]
pub fn stub_warnings_enabled() -> bool {
    WARN_ON_STUB.load(Ordering::Relaxed)
}
