// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 2b7c4bf60cde3101c4287d31213164d1767ce33e
//
#[allow(unused_imports)]
use tock_registers::interfaces::{Readable, Writeable};
pub trait TestSramPeripheral {
    fn set_dma_ram(&mut self, _ram: std::rc::Rc<std::cell::RefCell<caliptra_emu_bus::Ram>>) {}
    fn set_dma_rom_sram(&mut self, _ram: std::rc::Rc<std::cell::RefCell<caliptra_emu_bus::Ram>>) {}
    fn register_event_channels(
        &mut self,
        _events_to_caliptra: std::sync::mpsc::Sender<caliptra_emu_bus::Event>,
        _events_from_caliptra: std::sync::mpsc::Receiver<caliptra_emu_bus::Event>,
        _events_to_mcu: std::sync::mpsc::Sender<caliptra_emu_bus::Event>,
        _events_from_mcu: std::sync::mpsc::Receiver<caliptra_emu_bus::Event>,
    ) {
    }
    fn poll(&mut self) {}
    fn warm_reset(&mut self) {}
    fn update_reset(&mut self) {}
    fn generated(&mut self) -> Option<&mut TestSramGenerated> {
        None
    }
    fn read_sram(&mut self, index: usize) -> caliptra_emu_types::RvData {
        if let Some(generated) = self.generated() {
            return generated.read_sram(index);
        }
        0
    }
    fn write_sram(&mut self, val: caliptra_emu_types::RvData, index: usize) {
        if let Some(generated) = self.generated() {
            generated.write_sram(val, index);
        }
    }
}
#[derive(Clone, Debug)]
pub struct TestSramGenerated {
    sram: Vec<caliptra_emu_types::RvData>,
}
impl Default for TestSramGenerated {
    fn default() -> Self {
        Self {
            sram: vec![0 as caliptra_emu_types::RvData; 262144],
        }
    }
}
impl TestSramGenerated {
    pub fn new() -> Self {
        Self::default()
    }
    fn reset_state(&mut self) {
        *self = Self::default();
    }
}
impl TestSramPeripheral for TestSramGenerated {
    fn generated(&mut self) -> Option<&mut TestSramGenerated> {
        Some(self)
    }
    fn warm_reset(&mut self) {
        self.reset_state();
    }
    fn update_reset(&mut self) {
        self.reset_state();
    }
    fn read_sram(&mut self, index: usize) -> caliptra_emu_types::RvData {
        self.sram[index]
    }
    fn write_sram(&mut self, val: caliptra_emu_types::RvData, index: usize) {
        let write_val = (val) as caliptra_emu_types::RvData;
        let current_val = self.sram[index];
        let mut new_val = current_val;
        new_val = (new_val & !(0xffff_ffff as caliptra_emu_types::RvData))
            | (write_val & (0xffff_ffff as caliptra_emu_types::RvData));
        self.sram[index] = new_val;
    }
}
pub struct TestSramBus {
    pub periph: Box<dyn TestSramPeripheral>,
}
impl caliptra_emu_bus::Bus for TestSramBus {
    fn read(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
    ) -> Result<caliptra_emu_types::RvData, caliptra_emu_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(caliptra_emu_bus::BusError::LoadAddrMisaligned);
        }
        match addr {
            0..0x10_0000 => Ok(self.periph.read_sram(addr as usize / 4)),
            _ => Err(caliptra_emu_bus::BusError::LoadAccessFault),
        }
    }
    fn write(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
        val: caliptra_emu_types::RvData,
    ) -> Result<(), caliptra_emu_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(caliptra_emu_bus::BusError::StoreAddrMisaligned);
        }
        match addr {
            0..0x10_0000 => {
                self.periph.write_sram(val, addr as usize / 4);
                Ok(())
            }
            _ => Err(caliptra_emu_bus::BusError::StoreAccessFault),
        }
    }
    fn poll(&mut self) {
        self.periph.poll();
    }
    fn warm_reset(&mut self) {
        self.periph.warm_reset();
    }
    fn update_reset(&mut self) {
        self.periph.update_reset();
    }
}
