# Licensed under the Apache-2.0 license

[package]
name = "libtock_mcu_flash"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
libtock.workspace = true
libtock_platform.workspace = true
libtockasync.workspace = true
