# Licensed under the Apache-2.0 license

[package]
name = "emulator-bus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emulator-types.workspace = true
tock-registers.workspace = true
