# Licensed under the Apache-2.0 license

name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-24.04

    env:
      CARGO_INCREMENTAL: 0
      # Compiler warnings should fail to compile
      EXTRA_CARGO_CONFIG: "target.'cfg(all())'.rustflags = [\"-Dwarnings\"]"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Test commit name
        run: |
          echo "Build-Test: release_ref=$(git rev-parse HEAD)"

      - name: Install required packages
        run: |
          sudo apt-get update -qy && \
          sudo apt-get install -qy build-essential curl gcc-multilib gcc-riscv64-unknown-elf git rustup &&
          rustup toolchain install -c clippy,rust-src,llvm-tools,rustfmt,rustc-dev

      - name: Install cmake 3.x
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v3.31.6/cmake-3.31.6-linux-x86_64.tar.gz &&
          mkdir -p /opt/cmake &&
          tar xvzf cmake-3.31.6-linux-x86_64.tar.gz -C /opt/cmake --strip-components=1 &&
          echo "/opt/cmake/bin" >> $GITHUB_PATH

      - name: Check that Cargo.lock doesn't need to be updated
          # Note: this isn't the same as checking that Cargo.lock is up to date
          # (cargo update --locked), which makes sure that every package is the
          # latest published version. This is just ensuring that every
          # dependency has an entry in Cargo.lock that is compatible with the
          # version requirements in all Cargo.toml files.
        run: |
          # This works because cargo tree requires a Cargo.lock with no required updates
          cargo tree --locked > /dev/null || (
            echo "Please include required changes to Cargo.lock in your pull request"
            # Without the --locked flag, cargo will do the minimal possible update to Cargo.lock
            cargo tree > /dev/null 2> /dev/null
            # Print out the differences to ease debugging
            git diff Cargo.lock
            exit 1
          )

      - name: Run precheckin
        run: |
          cargo --config "$EXTRA_CARGO_CONFIG" xtask precheckin

      - name: Checkout spdm-emu repository
        uses: actions/checkout@v4
        with:
          repository: parvathib/spdm-emu
          ref: pbhogaraju/get-certificate
          path: spdm-emu
          submodules: recursive

      - name: Build spdm-emu
        run: |
          pushd spdm-emu
          git submodule update --init --recursive
          mkdir build
          pushd build
          cmake -DARCH=x64 -DTOOLCHAIN=GCC -DTARGET=Debug -DCRYPTO=mbedtls ..
          make copy_sample_key
          make
          popd
          popd

      - name: Run all tests
        run: |
          export SPDM_VALIDATOR_DIR=$GITHUB_WORKSPACE/spdm-emu/build/bin
          cargo --config "$EXTRA_CARGO_CONFIG" xtask test

      - name: Display SPDM Validator test results
        run: |
          cat $GITHUB_WORKSPACE/test.log
