# Licensed under the Apache-2.0 license

name: RISC-V Compliance tests

on:
  schedule:
    - cron: '0 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compliance:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Checkout riscv-isa-sim repository
      uses: actions/checkout@v4
      with:
        repository: riscv-software-src/riscv-isa-sim
        ref: 3f79e3b7ded80d9ef0e722126b3765207e010711
        path: riscv-isa-sim
    - name: Checkout sail-riscv repository
      uses: actions/checkout@v4
      with:
        repository: riscv/sail-riscv
        ref: 6a10cb76264d1eafccb61e22397bea4f2eced19b
        path: sail-riscv
    - name: Checkout RISC-V tests
      uses: actions/checkout@v4
      with:
        repository: riscv-non-isa/riscv-arch-test
        ref: 752c0fb721b9ab264682d491283d98813f95e45b
        path: emulator/compliance-test/riscv-arch-test
    - name: Install dependencies
      run: |
        sudo apt update && \
        sudo apt upgrade -y && \
        sudo apt install -y \
          device-tree-compiler \
          gcc-multilib \
          gcc-riscv64-unknown-elf \
          libgmp-dev \
          opam \
          rustup \
          z3
    - name: Rustup install
      run: |
        rustup toolchain install -c clippy,rust-src,llvm-tools,rustfmt,rustc-dev
    - name: Install RISC-V Python tools
      run: |
        pip install git+https://github.com/riscv/riscv-isac.git@777d2b47623d7eebdb8bbed06dbddedc33722346
        pip install git+https://github.com/riscv/riscof.git@9fe3597d75757c6c6198e034bbe62e8dceecc755
    - name: Build riscv-isa-sim
      working-directory: riscv-isa-sim
      run: |
        mkdir build
        cd build
        ../configure --prefix=/usr
        make -j$(nproc)
        sudo make install
    - name: Install Sail
      run: |
        opam init -a -y && \
        opam install -y sail.0.19.1 && \
        echo "$HOME/.opam/default/bin" >> "$GITHUB_PATH"
    - name: Build Sail RISC-V
      working-directory: sail-riscv
      run: |
        DOWNLOAD_GMP=FALSE ./build_simulators.sh
        sudo cp -r build/c_emulator/riscv_sim_rv32d /usr/bin/riscv_sim_RV32
    - name: Run compliance tests
      run: cargo run -p compliance-test -- --test_root_path emulator/compliance-test/riscv-arch-test
