name: FPGA Test Job

on:
  pull_request:
  push:
    branches: ["clundin/fpga-bootstrap-job"]
jobs:
  build_test_binaries:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/clundin25/caliptra-fpga-cross-compile-image:latest
    timeout-minutes: 60

    env:
      # Change this to a new random value if you suspect the cache is corrupted
      CACHE_BUSTER: abc0db888988

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Build test firmware
        run: |
          # Build ROM and runtime binaries
          cargo xtask rom-build --platform fpga
          cargo xtask runtime-build --platform fpga

          # Cross compile xtask for the ARM core
          cargo build -p xtask --target aarch64-unknown-linux-gnu

          mkdir -p /tmp/caliptra-binaries
          tar -cvz -f /tmp/caliptra-binaries/caliptra-binaries.tar.gz target/riscv32imc-unknown-none-elf/release/mcu-rom-fpga.bin target/riscv32imc-unknown-none-elf/release/runtime.bin target/aarch64-unknown-linux-gnu/debug/xtask

      - name: 'Upload test firmware artifact'
        uses: actions/upload-artifact@v4
        with:
          name: caliptra-test-firmware${{ inputs.artifact-suffix }}
          path: /tmp/caliptra-binaries
          retention-days: 1

  test_artifacts:
    runs-on: vck190-subsystem
    needs: build_test_binaries
    timeout-minutes: 120

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive' 

      - name: 'Download Test Firmware Artifact'
        uses: actions/download-artifact@v4
        with:
          name: caliptra-test-firmware${{ inputs.artifact-suffix }}
          path: /tmp/caliptra-binaries

      - name: Mount binaries
        run: |
          tar -xvf /tmp/caliptra-binaries/caliptra-binaries.tar.gz

      - name: Execute tests
        run: |
          export RUST_BACKTRACE=1
          sudo ./target/aarch64-unknown-linux-gnu/debug/xtask fpga-run --mcu-rom target/riscv32imc-unknown-none-elf/release/mcu-rom-fpga.bin

