# Licensed under the Apache-2.0 license

name: FPGA Tests

on:
  pull_request:
jobs:
  build_test_binaries:
    runs-on: [e2-standard-8]
    timeout-minutes: 60
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          
      - name: Install cross compiler
        run: |
          sudo apt-get update -qy && sudo apt-get install -y gcc-aarch64-linux-gnu squashfs-tools
          rustup toolchain install 1.84-x86_64-unknown-linux-gnu
          rustup target add riscv32imc-unknown-none-elf
          rustup target add aarch64-unknown-linux-gnu

      - name: Build test firmware
        run: |
          # Build ROM and runtime binaries
          cargo xtask rom-build --platform fpga
          cargo xtask runtime-build --platform fpga

          # Cross compile xtask for the ARM core
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER="aarch64-linux-gnu-gcc"
          cargo build -p xtask --target aarch64-unknown-linux-gnu

          mkdir -p /tmp/caliptra-binaries
          tar -cvz -f /tmp/caliptra-binaries/caliptra-binaries.tar.gz \
            target/riscv32imc-unknown-none-elf/release/mcu-rom-fpga.bin \
            target/riscv32imc-unknown-none-elf/release/runtime.bin \
            target/aarch64-unknown-linux-gnu/debug/xtask

      - name: 'Upload test firmware artifact'
        uses: actions/upload-artifact@v4
        with:
          name: caliptra-test-firmware${{ inputs.artifact-suffix }}
          path: /tmp/caliptra-binaries
          retention-days: 1

  test_artifacts:
    runs-on: vck190-mcu
    needs: build_test_binaries
    timeout-minutes: 120

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive' 

      - name: 'Download Test Firmware Artifact'
        uses: actions/download-artifact@v4
        with:
          name: caliptra-test-firmware${{ inputs.artifact-suffix }}
          path: /tmp/caliptra-binaries

      - name: Mount binaries
        run: |
          tar -xvf /tmp/caliptra-binaries/caliptra-binaries.tar.gz

      - name: Execute tests
        run: |
          export RUST_BACKTRACE=1
          sudo ./target/aarch64-unknown-linux-gnu/debug/xtask fpga-run --mcu-rom target/riscv32imc-unknown-none-elf/release/mcu-rom-fpga.bin
