# Licensed under the Apache-2.0 license

name: Nightly 2.1 Dispatcher

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  dispatch_nightly_main_2_1:
    uses: chipsalliance/caliptra-mcu-sw/.github/workflows/nightly.yml@main-2.1
