// Licensed under the Apache-2.0 license

use std::env;
use std::fs;
use std::path::PathBuf;

use caliptra_ocp_eat::ocp_profile::{
    ConciseEvidence, ConciseEvidenceMap, DebugStatus, EvTriplesMap, MeasurementFormat,
    OcpEatClaims, TaggedConciseEvidence,
};
use caliptra_ocp_eat::{CborEncodable, CborEncoder};

const NONCE_LEN: usize = 32;
const DEFAULT_CONCISE_EVIDENCE_WORKSPACE_SIZE: usize = 2048;
const CONCISE_EVIDENCE_WORKSPACE_SIZE_ENV: &str = "CALIPTRA_CONCISE_EVIDENCE_WORKSPACE_SIZE";

fn main() {
    println!("cargo:rerun-if-env-changed={CONCISE_EVIDENCE_WORKSPACE_SIZE_ENV}");
    write_eat_claims_template();
}

fn write_eat_claims_template() {
    let concise_evidence_workspace_size = concise_evidence_workspace_size();
    let nonce_marker = marker::<NONCE_LEN>(0xa0);
    let concise_evidence = template_concise_evidence();
    let encoded_concise_evidence = encode_to_vec(&concise_evidence);
    let encoded_concise_evidence_bstr = encode_bytes(&encoded_concise_evidence);
    let debug_status_key = encode_type_value(0, 263);
    let debug_status_marker = encode_type_value(0, DebugStatus::Disabled as u64);

    let measurement_format = [MeasurementFormat::new(&concise_evidence)];
    let claims = OcpEatClaims {
        nonce: &nonce_marker,
        dbgstat: DebugStatus::Disabled,
        eat_profile: OcpEatClaims::DEFAULT_PROFILE_OID,
        measurements: &measurement_format,
        issuer: None,
        cti: None,
        ueid: None,
        sueid: None,
        oemid: None,
        hwmodel: None,
        uptime: None,
        bootcount: None,
        bootseed: None,
        dloas: None,
        rim_locators: None,
        private_claims: &[],
    };

    let mut evidence_scratch = [0u8; 512];
    let template = encode_claims_to_vec(&claims, &mut evidence_scratch);
    let nonce_pos = find_subslice(&template, &nonce_marker).expect("nonce marker not found");
    let debug_status_key_pos =
        find_subslice_from(&template, &debug_status_key, nonce_pos + nonce_marker.len())
            .expect("debug status claim key not found");
    let debug_status_pos = debug_status_key_pos + debug_status_key.len();
    assert_eq!(
        template.get(debug_status_pos..debug_status_pos + debug_status_marker.len()),
        Some(debug_status_marker.as_slice()),
        "debug status marker did not follow debug status claim key"
    );
    let evidence_pos = find_subslice_from(
        &template,
        &encoded_concise_evidence_bstr,
        debug_status_pos + debug_status_marker.len(),
    )
    .expect("concise evidence marker not found");

    let mut generated = String::new();
    generated.push_str("// Licensed under the Apache-2.0 license\n");
    generated.push_str("// AUTO-GENERATED FILE. DO NOT EDIT.\n");
    generated.push_str("// Generated by attestation-evidence build.rs from caliptra-ocp-eat\n\n");
    generated.push_str(&format!(
        "pub const CONCISE_EVIDENCE_WORKSPACE_SIZE: usize = {concise_evidence_workspace_size};\n\n"
    ));
    write_bytes_const(&mut generated, "EAT_CLAIMS_PREFIX", &template[..nonce_pos]);
    write_bytes_const(
        &mut generated,
        "EAT_CLAIMS_EVIDENCE_PREFIX",
        &template[debug_status_pos + debug_status_marker.len()..evidence_pos],
    );
    write_bytes_const(
        &mut generated,
        "EAT_CLAIMS_DBGSTAT_PREFIX",
        &template[nonce_pos + nonce_marker.len()..debug_status_pos],
    );
    write_bytes_const(
        &mut generated,
        "EAT_CLAIMS_SUFFIX",
        &template[evidence_pos + encoded_concise_evidence_bstr.len()..],
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    fs::write(out_dir.join("eat_claims_template.rs"), generated)
        .expect("write generated EAT claims template");
}

fn concise_evidence_workspace_size() -> usize {
    match env::var(CONCISE_EVIDENCE_WORKSPACE_SIZE_ENV) {
        Ok(value) => value
            .parse::<usize>()
            .expect("CALIPTRA_CONCISE_EVIDENCE_WORKSPACE_SIZE must be a usize"),
        Err(env::VarError::NotPresent) => DEFAULT_CONCISE_EVIDENCE_WORKSPACE_SIZE,
        Err(env::VarError::NotUnicode(_)) => {
            panic!("CALIPTRA_CONCISE_EVIDENCE_WORKSPACE_SIZE must be valid UTF-8")
        }
    }
}

fn template_concise_evidence() -> ConciseEvidence<'static> {
    ConciseEvidence::Tagged(TaggedConciseEvidence {
        concise_evidence: ConciseEvidenceMap {
            ev_triples: EvTriplesMap {
                evidence_triples: Some(&[]),
                identity_triples: None,
                dependency_triples: None,
                membership_triples: None,
                coswid_triples: None,
                attest_key_triples: None,
            },
            evidence_id: None,
            profile: None,
        },
    })
}

fn marker<const N: usize>(start: u8) -> [u8; N] {
    let mut out = [0u8; N];
    for (idx, byte) in out.iter_mut().enumerate() {
        *byte = start.wrapping_add(idx as u8);
    }
    out
}

fn encode_claims_to_vec(claims: &OcpEatClaims<'_>, scratch: &mut [u8]) -> Vec<u8> {
    let mut out = [0u8; 1024];
    let len = {
        let mut encoder = CborEncoder::new(&mut out);
        claims
            .encode(&mut encoder, scratch)
            .expect("encode EAT claims template");
        encoder.len()
    };
    out[..len].to_vec()
}

fn encode_to_vec<T: CborEncodable>(value: &T) -> Vec<u8> {
    let mut out = [0u8; 512];
    let len = {
        let mut encoder = CborEncoder::new(&mut out);
        value.encode(&mut encoder).expect("encode template value");
        encoder.len()
    };
    out[..len].to_vec()
}

fn encode_bytes(bytes: &[u8]) -> Vec<u8> {
    let mut out = encode_type_value(2, bytes.len() as u64);
    out.extend_from_slice(bytes);
    out
}

fn encode_type_value(major_type: u8, value: u64) -> Vec<u8> {
    let major = major_type << 5;
    if value <= 23 {
        vec![major | value as u8]
    } else if value <= 0xff {
        vec![major | 24, value as u8]
    } else if value <= 0xffff {
        let mut out = vec![major | 25];
        out.extend_from_slice(&(value as u16).to_be_bytes());
        out
    } else if value <= 0xffff_ffff {
        let mut out = vec![major | 26];
        out.extend_from_slice(&(value as u32).to_be_bytes());
        out
    } else {
        let mut out = vec![major | 27];
        out.extend_from_slice(&value.to_be_bytes());
        out
    }
}

fn find_subslice(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    find_subslice_from(haystack, needle, 0)
}

fn find_subslice_from(haystack: &[u8], needle: &[u8], start: usize) -> Option<usize> {
    haystack
        .get(start..)?
        .windows(needle.len())
        .position(|window| window == needle)
        .map(|pos| start + pos)
}

fn write_bytes_const(out: &mut String, name: &str, bytes: &[u8]) {
    out.push_str(&format!("pub const {name}: &[u8] = &[\n"));
    for chunk in bytes.chunks(12) {
        out.push_str("    ");
        for byte in chunk {
            out.push_str(&format!("0x{byte:02x}, "));
        }
        out.push('\n');
    }
    out.push_str("];\n\n");
}
